version: "3.9"
services:
    postgres:
        image: ankane/pgvector:latest
        container_name: aila_postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: aila
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - pgdata:/var/lib/postgresql/data

    minio:
        image: minio/minio:RELEASE.2024-07-26T20-48-21Z
        container_name: aila_minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - miniodata:/data

    create-bucket:
        image: minio/mc:RELEASE.2024-07-18T15-06-36Z
        container_name: aila_minio_setup
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add local http://minio:9000 minioadmin minioadmin --api S3v4 &&
            /usr/bin/mc mb -p local/uploads || true &&
            /usr/bin/mc anonymous set download local/uploads || true &&
            exit 0
            "

volumes:
    pgdata:
    miniodata:
