version: "3.9"
services:
    postgres:
        image: ankane/pgvector:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: aila
        volumes:
            - pgdata:/var/lib/postgresql/data

    minio:
        image: minio/minio:RELEASE.2024-07-26T20-48-21Z
        environment:
            MINIO_ROOT_USER: ${S3_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
        command: server /data --console-address ":9001"
        volumes:
            - miniodata:/data

    api:
        build:
            context: ../../
            dockerfile: packages/api/Dockerfile
        depends_on:
            - postgres
            - minio
        environment:
            PORT: 4000
            DATABASE_URL: ${DATABASE_URL}
            AUTH_SECRET: ${AUTH_SECRET}
            LLM_PROVIDER: ${LLM_PROVIDER}
            LLM_API_KEY: ${LLM_API_KEY}
            NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
            S3_ENDPOINT: ${S3_ENDPOINT}
            S3_BUCKET: ${S3_BUCKET}
            PRISMA_SCHEMA_PATH: /app/prisma/schema.prisma

    web:
        build:
            context: ../../
            dockerfile: apps/web/Dockerfile
        environment:
            NEXT_PUBLIC_API_URL: http://api:4000
        depends_on:
            - api
        ports:
            - "3000:3000"

    admin:
        build:
            context: ../../
            dockerfile: apps/admin/Dockerfile
        environment:
            NEXT_PUBLIC_API_URL: http://api:4000
        depends_on:
            - api
        ports:
            - "3001:3001"

    caddy:
        image: caddy:2.8.4
        depends_on:
            - web
            - admin
            - api
        ports:
            - "80:80"
            - "443:443"
        environment:
            APP_DOMAIN: ${APP_DOMAIN}
            ADMIN_DOMAIN: ${ADMIN_DOMAIN}
            API_DOMAIN: ${API_DOMAIN}
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config

volumes:
    pgdata:
    miniodata:
    caddy_data:
    caddy_config:
