name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "packages/api/**"
      - "apps/web/**"
      - "apps/admin/**"
      - "Dockerfile"
      - "infra/docker/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_API: ghcr.io/${{ github.repository }}/api
      IMAGE_WEB: ghcr.io/${{ github.repository }}/web
      IMAGE_ADMIN: ghcr.io/${{ github.repository }}/admin
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/api/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.sha }}

      - name: Build and push Web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:latest
            ${{ env.IMAGE_WEB }}:${{ github.sha }}

      - name: Build and push Admin
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/admin/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_ADMIN }}:latest
            ${{ env.IMAGE_ADMIN }}:${{ github.sha }}

